name: Publish to NPM
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
          - uses: actions/checkout@v4.1.4
          - uses: actions/setup-node@v4.0.2
          - run: npm publish --access public
            env:
              NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
