name: Publish to NPM
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: actions/setup-node@v4.0.2
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: cat ./package.json
      - uses: 'phips28/gh-action-bump-version@master'
        with:
          skip-tag: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ secrets.NAME }}
          GITHUB_EMAIL: ${{ secrets.EMAIL }}
      - run: cat ./package.json
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
