name: Publish to NPM
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
          - uses: actions/checkout@v4.1.4
          - uses: actions/setup-node@v4.0.2
            with:
              registry-url: 'https://registry.npmjs.org'
          - run: npm publish
            env:
              NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
